### ISSUE TITLE
License and notes

### ISSUE THREAD

**Issue by TalAmuyal** [lgc-4/one.com-ddns-python-script#10]
Hi!

The script is working for me, thanks for sharing it!

Could you please set a license?

Also, I've noted a few things before it worked:
1. Having an authenticator for the account makes it impossible to connect, so it needs to be removed or use a guest accoint that doesn't have an authenticator.
2. The record needs to be already there, so the scripts can update an existing record, but not create a new one.

Could you please add a warning for these in the README?

Thanks again!

**Comment by lgc-4** [comment]
Hi, thanks for the feedback.

I will look into adding a license.

1. I didn't know one.com supported Two Factor Authentication. I will add an entry into the readme that the script does not support it. I might work on supporting it in the future.

2. That is already mentioned in the readme

> Note that the script is not capable of creating new DNS records.
> 
> It can only edit existing ones.

**Comment by TalAmuyal** [comment]
Oh.. sorry then, and thanks!
