### ISSUE TITLE
Move configuration into a separate file and/or add commandline options.

### ISSUE THREAD

**Issue by nilscript** [lgc-4/one.com-ddns-python-script#3]
Input data and program instructions should be separate to enable the configuration to be simpler and enable the program to accept different config files for different jobs. This is a rather simple job. I suggest using toml as a configuration language.

**Comment by lgc-4** [comment]
Moving discussion to pull request: https://github.com/LugicoHDPlayer/one.com-ddns-python-script/pull/4
